# Maven Package Workflow - This workflow will build a package using Maven and then publish it to GitHub Packages when a release is created.

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build and Push Docker Image
      run: |
        docker build -t secret-santa .
        docker tag secret-santa:latest tomicoazure/secret-santa:latest
        docker push tomicoazure/secret-santa:latest
        docker run -d --name tomico-n2 -p 8081:8081 tomicoazure/tomico-nodejs:latest

